# ビジネスグループ<SalesDept|CostomerService>
# 環境設定<Dev|IT|ST|Prod|DR>
bussinesGroupName: CostomerService
environmentName: Dev

# APIインスタンス
apiInstances:
  account-v1:
    assetId: account-cs
    apiInstanceLabel: Development

# ランタイム
runtime:
  domain: smpl-%s-account-v1
  filename: ../../account-v1/target/account-v1-1.0.0-SNAPSHOT-mule-application.jar
  apiIDkeys: 
    api.id: account-v1
  runtimeVersion: 4.4.0
  worker:
    # type: <Micro|Small|Medium|Large|xLarge|xxLarge|4xLarge>
    type: Micro
    workers: 1
    region: us-east-1
  properties:
    anypoint.platform.analytics_base_uri: https://analytics-ingest.anypoint.mulesoft.com/
  automaticallyRestart: true
  persistentQueues: false
  enableMonitoring: true

# SLA層
tiers:
  - tier:
    name: DevOps SLA Tier
    description: DevOps登録
    autoApprove: true
    maximumRequests: 5
    timePeriodInMilliseconds: 1

# ポリシー
policies:
 # JWT検証ポリシー
 jwt-validation:
   jwtKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiHeueaNGgYV6vyU/gHxFjcJ0aoLa3amxvPPdr5vd35qiKvpsBMV1oVyW5IwfDiBeF6kw5i9ZgbMshakmmVJdbgH4AE+cg2bWfAjTOIMN+1HdBlcbnBIZbn91nvmXAp/UYx+1EtRfur5Ykh481olKziuEyFuWgjB14WGyGz/uuPn8X2PlkNKrB983YrlXGwrkEtQpovDoj2L+ukKgKnVeIIrg3nQ6YHPTAC2ZOgYkVGY/gzUxba7Gj6BjV3m00FZArv2EnMfV0j/+VCC8CcknBIjLz9EgN/Z91L6zmEJT6D9ZVH78lDhpuX5miN1aIc4v/se2xZwGKHQCTxwwEZifqwIDAQAB
   clientIDExpression: "#[if(vars.claimSet.sub?) read(vars.claimSet.sub,'application/json').\"client_id\" else {}]"
   audienceClaimValues: api.sample.co.jp
 # SLAベースレイトリミット制限
 rate-limiting-sla-based:
   clientIDExpression: "#[if(authentication.properties.claims.sub?) read(authentication.properties.claims.sub,'application/json').\"client_id\" else {}]"
 # ヘッダー挿入
 header-injection:
   inboundItem: x-user-info
   inboundValue: "#[if(read(authentication.properties.claims.sub,'application/json').user_info?)read(authentication.properties.claims.sub,'application/json').user_info else {}]"
 # ヘッダー削除
 header-removal:
 # メッセージロギング
 message-logging:

# アラート
# - jwt-validation
# - rate-limiting-sla-based
# - api-response-time
# - api-response-code-500
# - api-response-code-400
# - api-request-count
alerts:
 - jwt-validation
 - rate-limiting-sla-based
 - api-response-time
 - api-response-code-500
 - api-response-code-400
 - api-request-count

# ランタイムアラート
# - cpu
# - deployment-failed
# - memory
# - worker-unresponsive
# - application-notification
# - event-threshold-exceeded
runtimeAlerts:
 - cpu
 - deployment-failed
 - memory
 - worker-unresponsive
 - application-notification
 - event-threshold-exceeded

# アラート受信者
# APIアラートとランタイムアラート両方の受信者を設定する。
alertRecipients:
 - user:
   userId: 4b95a083-ba48-4745-aa79-f4a8b4f610e4
   lastName: Kawaguchi
   firstName: Masaki
 - user:
   userId: 5ebd38e6-fde2-4967-811c-9461c998d49e
   lastName: Yamamoto
   firstName: Tarou
 - user:
   userId: fac27650-0433-4618-a613-4b171f1816bb
   lastName: Kimura
   firstName: Hanako

# リリース管理名
github:
 releaseName: account-v1-0.0.1
 fileName: account-v1-%s.jar
