name: MuleSoft CD account-v1 process script

# Trigger settings
on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Deploy The target applications.'
        required: false
        default: 'account-v1'
      env:
        description: 'Deploy The target environment.'
        required: false
        default: 'Sandbox'

# Job settings
jobs:
  # build script
  application-release:
    runs-on: ubuntu-latest
    env:
      API_ID : 17575290
      APP_NAME : smpl-dev-account-v1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Echo input parameter.
        run: |
          echo "The target application names are ${{ github.event.inputs.apps }}"
          echo "The target environment is ${{ github.event.inputs.env }}"

      - name: The Account-v1 API instance build process.
        run: APIBuilder-dev.sh
        shell: bash
        working-directory: ${{ github.event.inputs.apps }}
      
      - name: The Account-v1 archeve file download process.
        id: download
        run: mvn -s ../settings-master-dev.xml -f pom_deploy.xml dependency:copy
        shell: bash
        working-directory: ${{ github.event.inputs.apps }}
                
      - name: The Account-v1 archeve file deploy process.
        run: mvn -s ../settings-master-dev.xml -f pom_deploy.xml mule:deploy -Dautodiscovery.apiId=${{ env.API_ID }} -DapplicationName=${{ env.APP_NAME }}
        shell: bash
        working-directory: ${{ github.event.inputs.apps }}