name: MuleSoft Multi Dispatch CD process script

# Trigger settings
on:
  workflow_dispatch:
    inputs:
      appName1:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion1:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName2:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion2:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName3:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion3:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName4:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion4:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      env:
        description: 'Deploy The target environment.'
        required: false
        default: 'Sandbox'


jobs:
  deployJob1:
    if: github.event.inputs.appName1 != ''
    uses: Masaki-Rock/MultiProjectsDevOpsTest/.github/workflows/cd-deploy-workflow.yml@main
    with:
      appName: ${{ github.event.inputs.appName1 }}
      version: ${{ github.event.inputs.appVersion1 }}
      env: ${{ github.event.inputs.env }}

