name: MuleSoft Multi Dispatch CD process script

# Trigger settings
on:
  workflow_dispatch:
    inputs:
      appNameA:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersionA:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName2:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion2:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName3:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion3:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      appName4:
        description: 'Deploy The target applications.'
        required: false
        default: ''
      appVersion4:
        description: 'Deploy The target artifact version.'
        required: false
        default: '1.0.0-SNAPSHOT'
      env:
        description: 'Deploy The target environment.'
        required: false
        default: 'Sandbox'


jobs:
  deployJob1:
    if: github.event.inputs.appNameA != ''
    uses: Masaki-Rock/MultiProjectsDevOpsTest/.github/workflows/cd-deploy-workflow.yml@main
    with:
      appName: ${{ github.event.inputs.appName2 }}
      version: ${{ github.event.inputs.appVersion2 }}
      env: ${{ github.event.inputs.env }}

  deployJob2:
    if: github.event.inputs.appName2 != ''
    uses: Masaki-Rock/MultiProjectsDevOpsTest/.github/workflows/cd-deploy-workflow.yml@main
    with:
      appName: ${{ github.event.inputs.appName2 }}
      version: ${{ github.event.inputs.appVersion2 }}
      env: ${{ github.event.inputs.env }}

  deployJob3:
    if: github.event.inputs.appName3 != ''
    uses: Masaki-Rock/MultiProjectsDevOpsTest/.github/workflows/cd-deploy-workflow.yml@main
    with:
      appName: ${{ github.event.inputs.appName3 }}
      version: ${{ github.event.inputs.appVersion3 }}
      env: ${{ github.event.inputs.env }}

  deployJob4:
    if: github.event.inputs.appName4 != ''
    uses: Masaki-Rock/MultiProjectsDevOpsTest/.github/workflows/cd-deploy-workflow.yml@main
    with:
      appName: ${{ github.event.inputs.appName4 }}
      version: ${{ github.event.inputs.appVersion4 }}
      env: ${{ github.event.inputs.env }}
