name: MuleSoft CI account-v1 staging process script

# Trigger settings
on:
  push:
    branches: [ staging ]
    path: ['account-v1/*']
  pull_request:
    branches: [ staging ]
    path: ['account-v1/*']

# Job settings
jobs:
  # build script
  application-build:
    runs-on: ubuntu-latest
    env:
      PROJECT_HOME : ../../account-v1
      BRUANCH : staging
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the Mule application with Maven.
        run: mvn clean package -DattachMuleSources
        working-directory: account-v1
      
      - name: Upload the Mule application file to the release folder.
        run: java -jar app.jar -upload -token ${{ secrets.GITHUB_TOKEN }} -config ${{ env.PROJECT_HOME }} -branch ${{ env.BRUANCH }}
        shell: bash
        working-directory: .github/script