name: MuleSoft Contact-v1 CI process script

# Trigger settings
on:
  push:
    branches: [ main ]
    path: ['contact-v1/*']
  pull_request:
    branches: [ main ]
    path: ['contact-v1/*']

# Job settings
jobs:
  # build script
  application-build:
    runs-on: ubuntu-latest
    env:
      VERSION : 1.0.0-SNAPSHOT
      WORK_DIR : contact-v1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
 
      - name: Starting Build and Test.
        run: mvn clean verify
        working-directory: ${{ env.WORK_DIR }}
                  
      - name: Starting Build and Test.
        run: mvn clean verify
        working-directory: ${{ env.WORK_DIR }}

      - name: Setup new version.
        run: |
          mvn -f pom_publish.xml versions:set -DnewVersion=${{ env.VERSION }}
          mvn -f pom_publish.xml versions:commit
        working-directory: ${{ env.WORK_DIR }}
        
      - name: Publish the target mule application deploy file.
        run: mvn -s ../settings-master-dev.xml -f pom_publish.xml deploy
        shell: bash
        working-directory: ${{ env.WORK_DIR }}