name: Call a reusable workflow

on:
  workflow_call:
    inputs:
      appName:
        description: 'Deploy The target applications.'
        required: false
        type: string
        default: 'account-v1'
      version:
        description: 'Deploy The target artifact version.'
        required: false
        type: string
        default: '1.0.0-SNAPSHOT'
      env:
        description: 'Deploy The target environment.'
        required: false
        type: string
        default: 'Sandbox'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: echo ${{ github.event.inputs.appName }} ${{ github.event.inputs.version }} ${{ github.event.inputs.env }}